Repository chingu-voyages/v8-bears-team-06, pull requests merged in 2019-04, with the labels that each got.

#35 [Ready for Review] Added some stylings to user registration form and Updated Bootstrap to work properly
  client/components/Navbar.jsx
  client/components/layouts/Layout.jsx
  client/pages/signup.jsx
  server/graphql/schema.js
Labels: bug, enhancement

#33 [Ready for Review] Add Prototype Sign-in Page
  .babelrc
  client/components/Navbar.jsx
  client/components/SignInBox.jsx
  client/components/atom/Alert.jsx
  client/components/layouts/Layout.jsx
  client/context.js
  client/lib/init-apollo.js
  client/lib/redirect.js
  client/pages/_app.jsx
  client/pages/index.jsx
  client/pages/login.jsx
  client/pages/private.jsx
  client/pages/signup.jsx
  client/store/index.jsx
  logger.js
  package-lock.json
  package.json
  server/graphql/schema.js
  server/graphql/server.js
  server/index.js
Labels: enhancement

#40 package.json and db.js updated for heroku deployment
  package-lock.json
  package.json
  server/db.js
Labels: Deployment

#39 added client side password validation length check and alphanumeric...
  client/components/SignUpBox.jsx
  client/pages/signup.jsx
Labels: enhancement

#42 [Ready for Review] Authorize users in both server and client side
  client/pages/_app.jsx
  client/store/index.jsx
  package-lock.json
  package.json
  server/graphql/server.js
  server/index.js
Labels: enhancement

#43 Feature/test - Added Some Client-Side Tests For SignUpBox Component
  __test__/App.test.jsx
  __test__/__snapshots__/App.test.jsx.snap
  client/components/App.jsx
  client/components/SignUpBox.jsx
  client/components/SignUpBox.test.jsx
  client/components/__snapshots__/SignUpBox.test.jsx.snap
  package-lock.json
  package.json
Labels: To-do, enhancement

#52 Fix authentication related problems
  client/components/Navbar.jsx
  client/pages/_app.jsx
Labels: bug

#54 Fix security hole in GraphQL API
  client/lib/init-apollo.js
  server/graphql/middleware.js
  server/graphql/schema.js
  server/graphql/server.js
  server/graphql/server.test.js
Labels: bug

#57 Changed test environment to node for this file - default was JSDOM - Eliminates Mongoose-Jest Warning
  server/graphql/server.test.js
Labels: bug

#59 Return Email on Login and Set it in Context
  client/components/EditProfileBox.jsx
  client/components/SignInBox.jsx
  client/pages/editprofile.jsx
  client/pages/profile.jsx
  client/store/index.jsx
  server/db.js
  server/graphql/schema.js
  server/models/profile.js
Labels: To-do

#62 Update Authentication Middleware and Schema Resolver to Allow Authentication
  server/graphql/middleware.js
  server/graphql/schema.js
Labels: bug

#66 Refactor/user schema - Combined User and Profile Schemas
  server/db.js
  server/graphql/schema.js
  server/models/profile.js
  server/models/user.js
Labels: enhancement

#68 Refactor/update user name - Reduced User Name Fields to Single 'Name' Field
  client/components/EditProfileBox.jsx
  client/pages/profile/index.jsx
  server/db.js
  server/graphql/schema.js
  server/models/user.js
Labels: enhancement

#75 profile refactor
  src/client/components/EditProfileBox.jsx
  src/client/components/SignUpBox.jsx
  src/client/pages/profile/edit.jsx
  src/client/pages/profile/index.jsx
  src/client/pages/profile/queries.js
Labels: To-do

#81 Added background image to signup page and changed main heading
  src/client/components/SignUpBox.jsx
  src/client/components/SignUpBox.test.jsx
  src/client/components/__snapshots__/SignUpBox.test.jsx.snap
  src/client/pages/signup.jsx
  src/client/static/beach-cleanup.jpg
Labels: enhancement

#86 Feature/charities - Volunteers and Charities About Pages Added
  src/client/pages/charities.jsx
  src/client/pages/index.jsx
  src/client/pages/volunteers.jsx
  src/client/static/agriculture.jpg
  src/client/static/volunteer.jpg
Labels: To-do

#79 Added profile image upload functionality
  package-lock.json
  package.json
  src/client/components/ProfileCard.jsx
  src/client/next.config.js
  src/client/pages/profile/addimage.jsx
  src/client/pages/profile/edit.jsx
  src/client/pages/profile/index.jsx
  src/client/pages/profile/queries.js
  src/server/db.js
  src/server/graphql/schema.js
  src/server/models/user.js
Labels: enhancement

#87 make charities and volunteers pages public
  src/client/pages/_app.jsx
Labels: bug

#94 Footer
  src/client/components/Footer.jsx
  src/client/components/layouts/Layout.jsx
  src/client/pages/work/create.jsx
Labels: enhancement
